### ISSUE TITLE
error when trying to auto-connect to bridge

### ISSUE THREAD

**Issue by estiens** [ChristopherRogers1991/mycroft-hue#24]
installed on brand new picroft installation

```
04:52:26.509 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Phillips Hue Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 598, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 70, in handler
    or self.connected or self._connect_to_bridge():
  File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 210, in _connect_to_bridge
    self._attempt_connection()
  File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 176, in _attempt_connection
    self.ip = _discover_bridge()
  File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 456, in _discover_bridge
    sock.sendto(ssdpRequest, (SSDP_ADDR, SSDP_PORT))
TypeError: 'str' does not support the buffer interface
```

**Comment by ChristopherRogers1991** [comment]
Hello @estiens,

Thanks for reporting this. This seems like it's probably a python2 -> python3 issue that I've missed. I'll try to resolve it soon.

In the short term, you should be able to get yourself up and running by entering the IP address of your hub manually. You should be able to do that from the skills sedition at https://home.mycroft.ai.

Can you give that a shot, and let me know if it works?

**Comment by estiens** [comment]
yup, I wasn't able to get it to work when I updated the skill on home.mycroft (I tried to manually pull down the settings and restarted, no dice, but when I edited the JSON config file directly it found it right away!

**Comment by estiens** [comment]
Sure, do I need to wipe out the skill and re-install and try to pair again, or will it still try to auto-discover if I just wipe the IP from the config file?

**Comment by ChristopherRogers1991** [comment]
You'll just need to wipe the IP from the config, and then checkout that branch of the skill. I believe Mycroft should auto-reload the skill when you checkout the branch.

To checkout the branch, it should be something like:
```
cd /opt/mycroft/skills/mycroft-hue && git checkout bugfix/discover_bridge_p3
```
Assuming it works, I'll merge it to master, and you can revert back to the master branch with:
```
cd /opt/mycroft/skills/mycroft-hue && git checkout master
```

Let me know if you're able to do that. If you're not able and/or not comfortable with the command line stuff, let me know and I'll see if I can find another way to test it. Worst case, I'll just merge it to master. It already doesn't work, so I can't make things worse by merging it.

-Chris

**Comment by estiens** [comment]
yup no problem, seemed to work fine on that branch. just turned on and off the lights no problem. I didn't see anything about autodiscovery persay in the logs, but I killed settings.json, checked out your patch and then restarted the skills service and all worked fine.
